name: '1.2. Configure'

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:

  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    environment: production
    # needs: terraform

    defaults:
      run:
        shell: bash

    steps:

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Add SSH key to the GitHub Actions runner
    - name: Add SSH key
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > /home/runner/.ssh/ec2_id_rsa
        chmod 600 /home/runner/.ssh/ec2_id_rsa

    # Install Ansible
    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    # Install botocore and boto3 into Ansible pipx venv
    - name: Install boto3 and botocore into Ansible pipx venv
      run: |
        pipx inject ansible-core boto3 botocore

    # Check Ansible version
    - name: Check Ansible version
      run: ansible --version

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    
    # List all EC2 hosts from dynamic inventory
    - name: List EC2 hosts
      run: |
        ansible-inventory -i ansible-inventory.aws_ec2.yml --list

    # Ping all EC2 instances to check connectivity
    - name: Ping EC2 instances
      run: |
        ansible all -i ansible-inventory.aws_ec2.yml -m ping

    # Run the Ansible playbook to install Docker
    - name: Run Playbook "docker install"
      run: |
        ansible-playbook -i ansible-inventory.aws_ec2.yml ansible-docker-install.yml \
          --extra-vars "domain_name=${{ vars.DOMAIN_NAME }} email=${{ vars.EMAIL }}"

    # Run the Ansible playbook to deploy and configure Docker Compose applications
    - name: Run Playbook "docker up"
      run: |
        ansible-playbook -i ansible-inventory.aws_ec2.yml ansible-docker-up.yml \
          --extra-vars "domain_name=${{ vars.DOMAIN_NAME }} email=${{ vars.EMAIL }}"